In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('artvis_dataset.csv')
df.head(20)

a.id      a.firstname a.lastname a.gender a.birthdate a.deathdate  \
0      1  William Bernard     Adeney        M  1878-01-01  01-01-1966   
1      1  William Bernard     Adeney        M  1878-01-01  01-01-1966   
2      1  William Bernard     Adeney        M  1878-01-01  01-01-1966   
3      1  William Bernard     Adeney        M  1878-01-01  01-01-1966   
4      1  William Bernard     Adeney        M  1878-01-01  01-01-1966   
5      1  William Bernard     Adeney        M  1878-01-01  01-01-1966   
6      1  William Bernard     Adeney        M  1878-01-01  01-01-1966   
7      2            Peter       Alma        M  1886-01-01  01-01-1969   
8      2            Peter       Alma        M  1886-01-01  01-01-1969   
9      2            Peter       Alma        M  1886-01-01  01-01-1969   
10     2            Peter       Alma        M  1886-01-01  01-01-1969   
11     2            Peter       Alma        M  1886-01-01  01-01-1969   
12     2            Peter       Alma        M  1886-01-01  01-01-1969   
13     2            Peter       Alma        M  1886-01-01  01-01-1969   
14     3            Natan    Alt'man        M  1889-01-01  01-01-1970   
15     3            Natan    Alt'man        M  1889-01-01  01-01-1970   
16     3            Natan    Alt'man        M  1889-01-01  01-01-1970   
17     3            Natan    Alt'man        M  1889-01-01  01-01-1970   
18     3            Natan    Alt'man        M  1889-01-01  01-01-1970   
19     3            Natan    Alt'man        M  1889-01-01  01-01-1970   

   a.birthplace      a.deathplace a.nationality  e.id  \
0        London            London            GB   489   
1        London            London            GB   618   
2        London            London            GB   720   
3        London            London            GB   729   
4        London            London            GB   650   
5        London            London            GB   680   
6        London            London            GB   724   
7         Medan         Amsterdam            NL   716   
8         Medan         Amsterdam            NL   490   
9         Medan         Amsterdam            NL   609   
10        Medan         Amsterdam            NL   462   
11        Medan         Amsterdam            NL   462   
12        Medan         Amsterdam            NL   490   
13        Medan         Amsterdam            NL   609   
14     Vinnitsa  Saint Petersburg            RU  1482   
15     Vinnitsa  Saint Petersburg            RU  1302   
16     Vinnitsa  Saint Petersburg            RU  1481   
17     Vinnitsa  Saint Petersburg            RU   536   
18     Vinnitsa  Saint Petersburg            RU   615   
19     Vinnitsa  Saint Petersburg            RU   523   

                                              e.title  \
0   Second Post-Impressionist Exhibition. British,...   
1      Exhibition of the Camden Town Group and Others   
2   The Second Exhibition of Works by Members of t...   
3   Third Exhibition of Works by Members of the Lo...   
4   The First Exhibition of Works by Members of Th...   
5   Twentieth Century Art. A Review of Modern Move...   
6                                Vorticist Exhibition   
7     Tentoonstelling Alma, Le Fauconnier en Mondrian   
8   Moderne Kunst Kring (Cercle de l'art moderne)....   
9       Moderne Kunst Kring (Cercle de l'Art Moderne)   
10  Internationale Kunstausstellung des Sonderbund...   
11  Internationale Kunstausstellung des Sonderbund...   
12  Moderne Kunst Kring (Cercle de l'art moderne)....   
13      Moderne Kunst Kring (Cercle de l'Art Moderne)   
14                     Мир Искусства. Выставка картин   
15                    Выставка Картин "Мир Искусства"   
16                      Выставка Графических Искусств   
17                                      Мир искусства   
18                                      Мир Искусства   
19                                      Мир Искусства   

                                              e.venue  e.startdate e.type 

In [26]:
# Combine 'a.firstname' and 'a.lastname' into 'a.name'
df['a.name'] = df['a.firstname'] + ' ' + df['a.lastname']

# Drop 'a.firstname' and 'a.lastname' columns
df = df.drop(columns=['a.firstname', 'a.lastname'])

column_order = ['a.name'] + [col for col in df.columns if col != 'a.name']
df = df[column_order]



In [27]:
# Replace '\N' with NaN across all elements in the DataFrame
df = df.applymap(lambda x: np.nan if x == '\\N' else x)

# Show the updated DataFrame
print("DataFrame after replacing '\\N' with NaN:")
print(df)

C:\Users\yashl\AppData\Local\Temp\ipykernel_28900\1460889465.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: np.nan if x == '\\N' else x)


DataFrame after replacing '\N' with NaN:
                       a.name   a.id a.gender a.birthdate a.deathdate  \
0      William Bernard Adeney      1        M  1878-01-01  01-01-1966   
1      William Bernard Adeney      1        M  1878-01-01  01-01-1966   
2      William Bernard Adeney      1        M  1878-01-01  01-01-1966   
3      William Bernard Adeney      1        M  1878-01-01  01-01-1966   
4      William Bernard Adeney      1        M  1878-01-01  01-01-1966   
...                       ...    ...      ...         ...         ...   
72073     Adam Emory Albright  13998        M  1862-01-01  01-01-1957   
72074           Anna Davidson  13999        F  0000-01-01  0000-01-01   
72075           Anna Davidson  13999        F  0000-01-01  0000-01-01   
72076           Anna Davidson  13999        F  0000-01-01  0000-01-01   
72077           Anna Davidson  13999        F  0000-01-01  0000-01-01   

      a.birthplace a.deathplace a.nationality  e.id  \
0           London       Lo

In [5]:

# Step 2: Filter the data where 'e.city' is "Pittsburgh"
filtered_df = df[df['e.city'] == 'Pittsburgh'][['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df.to_csv("event_details_Pittsburgh.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df.info()


<class 'pandas.core.frame.DataFrame'>
Index: 1472 entries, 426 to 72073
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       1472 non-null   object
 1   e.latitude   1472 non-null   object
 2   e.longitude  1472 non-null   object
 3   e.city       1472 non-null   object
 4   e.type       1472 non-null   object
 5   e.startdate  1472 non-null   int64 
 6   e.venue      1472 non-null   object
dtypes: int64(1), object(6)
memory usage: 92.0+ KB


In [6]:
filtered_df.head(10)

a.name e.latitude e.longitude      e.city e.type  \
426          George Wesley Bellows    40.4333    -79.9833  Pittsburgh  group   
431          George Wesley Bellows    40.4333    -79.9833  Pittsburgh  group   
432          George Wesley Bellows    40.4333    -79.9833  Pittsburgh  group   
433          George Wesley Bellows    40.4333    -79.9833  Pittsburgh  group   
1128               Eugène Carrière    40.4333    -79.9833  Pittsburgh  group   
1469                  Walter Crane    40.4333    -79.9833  Pittsburgh  group   
1560           Arthur Bowen Davies    40.4333    -79.9833  Pittsburgh  group   
1881  Georges-Olivier Desvallières    40.4333    -79.9833  Pittsburgh  group   
2791        William James Glackens    40.4333    -79.9833  Pittsburgh  group   
3090                  Robert Henri    40.4333    -79.9833  Pittsburgh  group   

      e.startdate             e.venue  
426          1910  Carnegie Institute  
431          1912  Carnegie Institute  
432          1913  Carnegie Institute  
433          1914  Carnegie Institute  
1128         1912  Carnegie Institute  
1469         1905  Carnegie Institute  
1560         1913  Carnegie Institute  
1881         1912  Carnegie Institute  
2791         1905  Carnegie Institute  
3090         1910  Carnegie Institute

In [7]:
year=filtered_df['e.startdate'].unique()
print(year)



[1910 1912 1913 1914 1905 1911 1909]


In [8]:
name=filtered_df['a.name'].unique()
print(name)
# Count the number of unique names in the 'a.name' column
unique_name_count = filtered_df['a.name'].nunique()

# Print the result
print(f"Number of unique names: {unique_name_count}")

# Get the top 10 most frequent unique names and their counts
top_10_names = filtered_df['a.name'].value_counts().head(10)

# Print the result
print("Top 10 most frequent names and their counts:")
print(top_10_names)



['George Wesley Bellows' 'Eugène Carrière' 'Walter Crane'
 'Arthur Bowen Davies' 'Georges-Olivier Desvallières'
 'William James Glackens' 'Robert Henri' 'Augustus John' 'Ernest Lawson'
 'George Benjamin Luks' 'Alfred Henry Maurer' 'Claude Monet'
 'Jan Preisler' 'Leo Putz' 'Pierre-Auguste Renoir' 'John Sloan'
 'John Henry Twachtman' 'Franz von Stuck' 'Anders Zorn' 'Hans Borchardt'
 'Ludwig Dill' 'Rudolf Nissl' 'Richard Pietzsch' 'Georg Sauter'
 'Ulrich Hübner' 'Charles Tooby' 'Hans Richard von Volkmann'
 'Heinrich von Zügel' 'Benno Becker' 'Josef Engelhart' 'Albert Besnard'
 'Richard Harlfinger' 'Jacques-Emile Blanche' 'George Clausen'
 'Charles Cottet' 'Ludwig Dettmann' 'Theodor Esser'
 'Thomas Alexander Harrison' 'Emanuel Hegenbarth' 'Julius Paul Junghanns'
 'Richard Kaiser' 'Heinrich Knirr' 'John Lavery' 'Henry Muhrmann'
 'Joseph Oppenheimer' 'James Paterson' 'Bertram Priestman'
 'Rudolf Schramm-Zittau' 'Alfred Withers' 'Gaston de Latouche'
 'Heinrich Beecke' 'Ernst Burmester' 'Max C

In [9]:
year=filtered_df['e.startdate'].unique()
print(year)



[1910 1912 1913 1914 1905 1911 1909]


In [10]:

# Step 2: Filter the data where 'e.city' is "London"
filtered_df1 = df[df['e.city'] == 'New York'][['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df1.to_csv("event_details_New_York.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df1.info()

year1=filtered_df1['e.startdate'].unique()
print(year1)

<class 'pandas.core.frame.DataFrame'>
Index: 949 entries, 76 to 71067
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       949 non-null    object
 1   e.latitude   949 non-null    object
 2   e.longitude  949 non-null    object
 3   e.city       949 non-null    object
 4   e.type       949 non-null    object
 5   e.startdate  949 non-null    int64 
 6   e.venue      949 non-null    object
dtypes: int64(1), object(6)
memory usage: 59.3+ KB
[1913 1909 1908 1912 1911 1915 1910 1914]


In [11]:

# Step 2: Filter the data where 'e.city' is "London"
filtered_df2 = df[df['e.city'] == 'Chicago'][['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df2.to_csv("event_details_Chicago.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df2.info()

year2=filtered_df2['e.startdate'].unique()
print(year2)

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 140 to 52636
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       183 non-null    object
 1   e.latitude   183 non-null    object
 2   e.longitude  183 non-null    object
 3   e.city       183 non-null    object
 4   e.type       183 non-null    object
 5   e.startdate  183 non-null    int64 
 6   e.venue      183 non-null    object
dtypes: int64(1), object(6)
memory usage: 11.4+ KB
[1913 1905]


In [12]:

# Step 2: Filter the data where 'e.city' is "London"
filtered_df3 = df[df['e.city'] == 'Boston'][['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df3.to_csv("event_details_Boston.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df3.info()



<class 'pandas.core.frame.DataFrame'>
Index: 59 entries, 142 to 25774
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       59 non-null     object
 1   e.latitude   59 non-null     object
 2   e.longitude  59 non-null     object
 3   e.city       59 non-null     object
 4   e.type       59 non-null     object
 5   e.startdate  59 non-null     int64 
 6   e.venue      59 non-null     object
dtypes: int64(1), object(6)
memory usage: 3.7+ KB


In [13]:
year3=filtered_df3['e.startdate'].unique()
print(year3)

[1913]


In [14]:

# Step 2: Filter the data where 'e.city' is "London"
filtered_df5 = df[df['e.city'] == 'Cincinnati'][['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df5.to_csv("event_details_Cincinnati.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df5.info()
year5=filtered_df5['e.startdate'].unique()
print(year5)

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 1854 to 52635
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       21 non-null     object
 1   e.latitude   21 non-null     object
 2   e.longitude  21 non-null     object
 3   e.city       21 non-null     object
 4   e.type       21 non-null     object
 5   e.startdate  21 non-null     int64 
 6   e.venue      21 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.3+ KB
[1905]


In [15]:
# Step 2: Filter the data where 'e.city' is "London"
filtered_df6 = df[df['e.city'] == 'Dresden'][['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df6.to_csv("event_details_Dresden.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df6.info()

year6=filtered_df6['e.startdate'].unique()
print(year6)

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 26 to 69655
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       183 non-null    object
 1   e.latitude   183 non-null    object
 2   e.longitude  183 non-null    object
 3   e.city       183 non-null    object
 4   e.type       183 non-null    object
 5   e.startdate  183 non-null    int64 
 6   e.venue      183 non-null    object
dtypes: int64(1), object(6)
memory usage: 11.4+ KB
[1910 1914 1906 1912]


In [16]:
# Step 2: Filter the data where 'e.city' is "London"
filtered_df7 = df[df['e.city'] == 'San Francisco'][['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df7.to_csv("event_details_San_Francisco.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df7.info()

year7=filtered_df7['e.startdate'].unique()
print(year7)

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 289 to 289
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       1 non-null      object
 1   e.latitude   1 non-null      object
 2   e.longitude  1 non-null      object
 3   e.city       1 non-null      object
 4   e.type       1 non-null      object
 5   e.startdate  1 non-null      int64 
 6   e.venue      1 non-null      object
dtypes: int64(1), object(6)
memory usage: 64.0+ bytes
[1915]


In [17]:
# Step 2: Filter the data where 'e.city' is "London"
filtered_df8 = df[['a.name', 'e.latitude', 'e.longitude', 'e.city','e.type','e.startdate','e.venue']]


# Step 5: Save the filtered table to a new CSV file
filtered_df7.to_csv("event_details_San_Francisco.csv", index=False)

# Optionally, display the first few rows of the filtered table
filtered_df7.info()

year7=filtered_df7['e.startdate'].unique()
print(year7)

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 289 to 289
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   a.name       1 non-null      object
 1   e.latitude   1 non-null      object
 2   e.longitude  1 non-null      object
 3   e.city       1 non-null      object
 4   e.type       1 non-null      object
 5   e.startdate  1 non-null      int64 
 6   e.venue      1 non-null      object
dtypes: int64(1), object(6)
memory usage: 64.0+ bytes
[1915]


In [44]:
import pandas as pd

# Step 1: Parse dates and extract years
df['birth_year'] = pd.to_datetime(df['a.birthdate'], errors='coerce').dt.year
df['death_year'] = pd.to_datetime(df['a.deathdate'], errors='coerce').dt.year

# Remove rows with NaN values in birth_year or death_year
df = df.dropna(subset=['birth_year', 'death_year','a.nationality','a.gender','a.birthplace','a.deathplace'])

# Save dataset with years to a CSV file
df.to_csv('dataset_with_years.csv', index=False)

# Step 2: Filter the data and include the necessary columns with renamed 'gender'
filtered_df8 = df[[
    'a.name', 'birth_year', 'death_year', 'a.gender','a.nationality','a.birthplace','a.deathplace']]

# Rename 'a.gender' to 'gender'
filtered_df8 = filtered_df8.rename(columns={'a.gender': 'gender'})
filtered_df8 = filtered_df8.rename(columns={'a.birthplace': 'placeofbirth'})
filtered_df8 = filtered_df8.rename(columns={'a.deathplace': 'placeofdeath'})
filtered_df8 = filtered_df8.rename(columns={'a.nationality': 'nationality'})
filtered_df8 = filtered_df8.rename(columns={'a.name': 'name'})

# Keep only unique rows and remove NaN values
filtered_df8 = filtered_df8.drop_duplicates()

# Save the filtered DataFrame to a new CSV file
filtered_df8.to_csv("artist_birth_death.csv", index=False)

# Optionally, display the first few rows of the filtered DataFrame
filtered_df8.info()


<class 'pandas.core.frame.DataFrame'>
Index: 8623 entries, 0 to 72073
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   name          8623 non-null   object
 1   birth_year    8623 non-null   int32 
 2   death_year    8623 non-null   int32 
 3   gender        8623 non-null   object
 4   nationality   8623 non-null   object
 5   placeofbirth  8623 non-null   object
 6   placeofdeath  8623 non-null   object
dtypes: int32(2), object(5)
memory usage: 471.6+ KB


In [43]:
filtered_df8.head()


a.name  birth_year  death_year gender nationality  \
0   William Bernard Adeney        1878        1966      M          GB   
7               Peter Alma        1886        1969      M          NL   
14           Natan Alt'man        1889        1970      M          RU   
26              Cuno Amiet        1868        1961      M          CH   
57       Vassily Kandinsky        1866        1944      M          RU   

   placeofbirth       placeofdeath  
0        London             London  
7         Medan          Amsterdam  
14     Vinnitsa   Saint Petersburg  
26    Solothurn            Seeberg  
57       Moscow  Neuilly-sur-Seine

In [36]:
filtered_df8.head()

a.name  birth_year  death_year gender a.nationality
0   William Bernard Adeney        1878        1966      M            GB
7               Peter Alma        1886        1969      M            NL
14           Natan Alt'man        1889        1970      M            RU
26              Cuno Amiet        1868        1961      M            CH
57       Vassily Kandinsky        1866        1944      M            RU